### PR TITLE
Print list of reviewers for opened PRs

### PR DESCRIPTION
**Pull request by nabcos**
Slightly changed the message format, extract reviewers user names for new pull requests.

### CODE REVIEW

**Comment by cskeppstedt** [comment]
Hi @nabcos, thanks for contributing! Some notes:
- What happens if there are 0 reviewers? I think the text will say `Opened: #id (title) for  #url"`. I think it would be improved by not writing the "for  " part in case of an empty array.
- I also think it would be nice with some spaces in between the names, e.g. `... for a, b, c #url`
- Last but not least, the tests seem to be failing because there's a `<br/>` in the expects.

**Comment by nabcos** [comment]
Should all be fixed with the last three commits.

**Comment by cskeppstedt** [comment]
@nabcos cool! I will review it this week, sorry for being a slowpoke.

**Comment by nabcos** [comment]
@cskeppstedt ping ;)

**Pull request closed without merging**
